# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
    ]
