# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20160301_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
